---

- name: download wp-cli.phar
  command: wget https://github.com/wp-cli/wp-cli/releases/download/v0.13.0/wp-cli.phar

- name: chmod +x wp-cli.phar
  command: chmod +x wp-cli.phar

- name: mv wp-cli.phar /usr/local/bin/wp
  command: mv wp-cli.phar /usr/local/bin/wp
