---
# tasks file for apache2
# update for apache 2.4
# use the name vhost.conf instead of vhost so a2ensite would find it

- name: install packages {{ item }}
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2-mpm-worker
  notify:
    - start apache2

- name: copy vhosts to vm
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/{{ item.vhost_name }}.conf
             owner=root group=root mode=0644
  with_items: apache2_vhosts 

- name: create website dirs
  file: path={{ item.dir }} owner=www-data group=www-data mode=0755
        state=directory
  with_items: apache2_vhosts  

- name: disable default site
  command: a2dissite 000-default

- name: enable vhosts
  command: a2ensite {{ item.vhost_name }}
  with_items: apache2_vhosts
  notify:
    - restart apache2
