- name: install supervisor and beanstalkd
  apt: pkg={{ item }} state=latest
  with_items:
    - supervisor
    - beanstalkd

- name: backup supervisord.conf
  command: creates=/etc/supervisor/supervisord.conf.orig chdir=/etc/supervisor
           cp supervisord.conf supervisord.conf.orig

- name: copy beanstalkd.conf to server
  template: src=beanstalkd.conf dest=/etc/supervisor/conf.d/beanstalkd.conf 
            owner=root group=root mode=0644
  notify:
    - stop supervisor
    - start supervisor

