---
sites:
  - user: sonnenglas 
    dir: site1 
    php_pool: 9001 
    server_name: uk1.example.com

  - user: user2 
    dir: site2 
    php_pool: 9002 
    server_name: www.site2.com 

