#- name: add sudo nopasswd option for user op
#  shell: creates=/etc/sudoers.d/op 
#         echo "op ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/op &&
#         chmod 0440 /etc/sudoers.d/op

- name: set locale
  shell: echo 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"' > /etc/default/locale

- name: install packages for ansible
  apt: pkg={{ item }} state=latest
  with_items:
    - python-jinja2
    - python-yaml
    - python-virtualenv

- name: install common packages
  apt: pkg={{ item }} state=latest
  with_items: 
    - vim
    - htop
    - git
