#test one playbook a time
---
- hosts: localhost 
  sudo: True 
  gather_facts: False

  #roles:
    #- virutalbox

  tasks:
  #- include: desktop.yml
    - include: base.yml
    - include: configure_git.yml
    - include: tools.yml
