---
- name: run playbooks via root
  hosts: localhost 
  sudo: True 
  gather_facts: False

  #roles:
    #- virutalbox

  tasks:
    - include: base.yml
    - include: configure_git.yml
    - include: tools.yml
    - include: python_packages.yml
    - include: desktop.yml


- name: run playbooks for current user
  hosts: localhost 
  sudo: False 
  gather_facts: False

  tasks:
    - include: configure_git.yml
