- name: install some packages
  apt: pkg={{ item }} state=latest
  with_items:
    - python-pip
    - python-mysqldb
    - python-pycurl
    - unzip
  tags:
    - packages
    - clients

- name: install ansible using pip
  pip: name=ansible
