- name: install some packages
  apt: pkg={{ item }} state=latest
  with_items:
    - python-pip
    - python2.7-dev
    # - python-mysqldb
    - python-pycurl
    - unzip
  tags:
    - packages
    - clients

- name: mkdir -p /etc/ansible
  file: path=/etc/ansible state=directory
        owner=root group=root mode=0755
  tags:
    - config

- name: copy ansible.cfg and hosts files
  copy: src=/etc/ansible/{{ item }} dest=/etc/ansible/{{ item }}
  with_items:
    - ansible.cfg
    - hosts
  tags:
    - config

- name: install ansible using pip
  pip: name=ansible state=latest
