---
- name: install fail2ban
  apt: pkg=fail2ban state=latest
  notify:
    - start fail2ban

- name: copy jail.conf to server
  template: src=jail-web.conf dest=/etc/fail2ban/jail.conf
            owner=root group=root mode=0644
  notify:
    - restart fail2ban
