---

- name: Launch instance
  local_action: ec2 keypair={{ keypair }}  instance_type={{ instance_type }} 
                image={{ image }} region={{ region }} 
                aws_access_key={{ aws_access_key }} 
                aws_secret_key={{ aws_secret_key }} 
                group={{ security_group }} wait=true   
                #user_data="{{ lookup('file', 'cloud-init.yml') }}"
  register: ec2

- name: Add new instance to host group
  local_action: add_host hostname={{ item.public_ip }} groupname=launched
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 
                delay=60 timeout=320 state=started
  with_items: ec2.instances


