---
- hosts: web
  sudo: yes
  
  tasks:
  - include: roles/fail2ban/tasks/main.yml

  handlers:
  - include: roles/fail2ban/handlers/main.yml

- hosts: awx
  sudo: yes

  tasks:
  - include: roles/fail2ban/tasks/awx.yml

  handlers:
  - include: roles/fail2ban/handlers/main.yml
