#need to specify -e pool_name=poolname on the command line
---
- hosts: web 
  sudo: yes
  vars:
    - pool_name: pool2

  tasks:
    - include: roles/php5/tasks/remove-pool.yml

  handlers:
    - include: roles/php5/handlers/main.yml
